##############################
# Hugo site config
##############################

title = "Zoran Person"
baseURL = 'https://zoranzhou.com/'
theme = "gokarna"

languageCode = 'en-us'

# This defines how dates are formatted
defaultContentLanguage = "en-gb"

# Enable emojis globally
enableEmoji = true