##############################
# Hugo site config (TOML)
##############################
title = "ZORAN PERSON"
baseURL = "https://zoranzhou.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]
disqusShortname = ""

##############################
# Pagination (Hugo v0.128+)
##############################
[pagination]
pagerSize = 10

##############################
# Params
##############################
[params]
TocSide = "left"
EnableInstantClick = true

##############################
# Menu
##############################
[menu]
  [[menu.main]]
  name = "ZORAN"
  url = "https://zoranzhou.com"

    [menu.main.params]
    external = true
