##############################
# Hugo site config (TOML)
##############################
title = "ZORAN PERSON"
baseURL = "https://zoranzhou.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]
disqusShortname = ""

##############################
# Pagination (Hugo v0.128+)
##############################
[pagination]
pagerSize = 10

##############################
# Params
##############################
[params]
TocSide = "left"
EnableInstantClick = false

# --- Logo 配置（新增） ---
[params.logo]
icon = "logo.png"     # 放在 /assets/logo.png
iconWidth = 32        # 可自行调整
iconHeight = 32
text = ""             # 不显示“ZORAN PERSON”文字

##############################
# Menu
##############################
[menu]

  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 2
  
  [[menu.main]]
  name = "Archives"
  url = "/archives/"
  weight = 3
    [menu.main.params]
    external = false

# --- Social Icons ---
[[params.social]]
name = "github"
url = "https://github.com/zoran-sid"

[[params.social]]
name = "twitter"
url = "https://x.com/zhouzoran75607"

[[params.social]]
name = "email"
url = "zoranzhou28@gmail.com"

[[params.social]]
name = "instagram"
url = "https://www.instagram.com/zoranzhou"

[[params.social]]
name = "bilibili"
url = "https://space.bilibili.com/596163308"

##############################
# Comments (Waline)
##############################
[params.commentSystems.waline]
serverURL = "https://zoranzhou.cn"
locale = "en"
dark = "auto"

[params.defaultCommentSystems]
waline = true
