##############################
# Hugo site config (TOML)
##############################
title = "ZORAN PERSON"
baseURL = "https://zoranzhou.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]
disqusShortname = ""

##############################
# Pagination (Hugo v0.128+)
##############################
[pagination]
pagerSize = 10

##############################
# Params
##############################
[params]
TocSide = "left"
EnableInstantClick = false

##############################
# Menu
##############################
[menu]

  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 2

  [[menu.main]]
  name = "Newsletter"
  url = "/newsletter/"
  weight = 3
  
  [[menu.main]]
  name = "Archives"
  url = "/archives/"
  weight = 4

    [menu.main.params]
    external = true

# --- Social Icons ---
[[params.social]]
name = "github"
url = "https://github.com/zoran-sid"

[[params.social]]
name = "instgram"
url = "https://www.instagram.com/zoranzhou"

[[params.social]]
name = "twitter"
url = "https://x.com/zhouzoran75607"

[[params.social]]
name = "email"
url = "zoranzhou28@gmail.com"

[params.commentSystems.waline]
serverURL = "https://zoranzhou.cn"
locale = "en"
dark = "auto"

[params.defaultCommentSystems]
waline = true