##############################
# Hugo site config (TOML)
##############################
title = "ZORAN PERSON"
baseURL = "https://zoranzhou.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]
disqusShortname = ""
paginate = 10

##############################
# Params
##############################
[params]
TocSide = "left"
EnableInstantClick = true   # 如果你的主题需要布尔值，可改 true/false

##############################
# Menu
##############################
[menu]

  [[menu.main]]
  name = "ZORAN"
  url = "https://zoranzhou.com"
  
    [menu.main.params]
    external = true
