title = "ZORAN"
baseURL = "https://zoranzhou.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]
disqusShortname = ""


[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML"]

##############################
# Pagination
##############################
[pagination]
pagerSize = 10

##############################
# Params
##############################
[params]
TocSide = "left"
EnableInstantClick = false
defaultTheme = "auto"
disableThemeToggle = false
# --- Logo ---
[params.logo] 
icon = "favicon.png"
appleTouchIcon = "img/apple-touch-icon.png" 
iconWidth = 128        
iconHeight = 128
text = ""             

##############################
# Menu
##############################
[menu]

  [[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 1
  
  [[menu.main]]
  name = "Essays"
  url = "/essays/"
  weight = 2

  [[menu.main]]
  name = "Search"
  url = "/search/"
  weight = 3 

  [[menu.main]]
  name = "Archives"
  url = "/archives/"
  weight = 4
  
  [menu.main.params]
    external = false
	
[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

# --- Social Icons ---
[[params.social]]
name = "github"
url = "https://github.com/zoran-sid"

[[params.social]]
name = "twitter"
url = "https://x.com/zhouzoran75607"

[[params.social]]
name = "facebook"
url = "https://www.facebook.com/share/1AQECFT4ui/?mibextid=wwXIfr"

[[params.social]]
name = "instagram"
url = "https://www.instagram.com/zoranzhou"

[[params.social]]
name = "bilibili"
url = "https://space.bilibili.com/596163308"

##############################
# Comments
##############################
[params.commentSystems.waline]
serverURL = "https://zoranzhou.cn"
locale = "en"

[params.defaultCommentSystems]
waline = true
